# Generated by Django 6.0.2 on 2026-02-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_externalsearchaudit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditor',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='encrypteddocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='auditor',
            name='key_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='externalsearchaudit',
            name='key_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='externalsearchaudit',
            name='keyword_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='externalsearchaudit',
            index=models.Index(fields=['keyword_hash'], name='documents_e_keyword_14a49c_idx'),
        ),
        migrations.AddIndex(
            model_name='searchtokenindex',
            index=models.Index(fields=['external_token'], name='documents_s_externa_6b6d9a_idx'),
        ),
    ]
